### ISSUE TITLE
关于默认管理员邮箱更改问题

### ISSUE THREAD

**Issue by Rladmsrl** [crper/yapi-docker#1]
您好我想问一下为什么我改了config里的邮箱以后重启docker/服务器。登陆账号还是您的那个outlook邮箱啊，怎么更改管理员登陆账号啊，谢谢

找到方法了

**Comment by xinsir88** [comment]
是什么方法，求告知

**Comment by Rladmsrl** [comment]
> 是什么方法，求告知

去数据库改就行

**Comment by david-0512** [comment]
docker 里修改yapi 管理员邮件地址操作步骤求操作步骤。
